### ISSUE TITLE
Not anywhere near useable

### ISSUE THREAD

**Issue by docwilmot** [backdrop-contrib/facetapi#1]
Code as of today 10 March 2019 allows install but it is not ready for use.

**Comment by earlyburg** [comment]
I'd like to say that I am working on this to try to get it usable for all.
I feel we may also need an official port of:
https://www.drupal.org/project/search_api_solr
https://www.drupal.org/project/search_api_page
I checked for these projects in backdrop-contrib/ but I did not find them.
If they existed I would create plenty of pull requests :)

**Comment by earlyburg** [comment]
Usable - thanks to all the help from everyone.
