### ISSUE TITLE
Install file can't run updates

### ISSUE THREAD

**Issue by oriolroger** [backdrop-contrib/facetapi#11]
Hi, I'm trying to install this module from a Drupal 7 migration, and the update.php script can't find a valid update function to run.

It seems that all the functions "facetapi_update_7xxx" in the facetapi.install file are not detected, and the good one (facetapi_update_1000) is never executed.

The returned error is: "_`facetapi module can not be updated. Its schema version is 0. Updates up to and including 7104 have been removed in this release. In order to update facetapi module, you will first need to upgrade to the last version in which these updates were available.`_"

To get this update function running, I had to delete all the old ones ("facetapi_update_7xxx"), and run the update.php script again.

Thanks.

**Comment by oriolroger** [comment]
I've seen that just removing the function _**facetapi_update_last_removed()**_ solves the problem.

**Comment by argiepiano** [comment]
My guess is that you tried to upgrade a D7 site that was using an old Facet API module version, or a D7 site where the last update of Facet API had not run.

**Comment by argiepiano** [comment]
Closing on behalf of the @backdrop-contrib/bug-squad as there is no more activity here.
