### ISSUE TITLE
PHP 8.1: Deprecated function: Return type of FacetapiFacet::offsetExists($offset) should either be compatible with ArrayAccess

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/facetapi#14]
When running this module on PHP 8.1, I'm getting:

`Deprecated function: Return type of FacetapiFacet::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in require_once() (line 1131 of... Sites/localhost/panettone/modules/facetapi/plugins/adapter.inc)`.

This is similar to several other places in core and contrib where we've had to add  `#[\ReturnTypeWillChange]` right above the offending methods.

**Comment by herbdool** [comment]
@argiepiano feel like making a PR? I can test it and we can merge it later as part of Bug Squad.

**Comment by argiepiano** [comment]
Done! PR #18

**Comment by herbdool** [comment]
LGTM

**Comment by argiepiano** [comment]
I'll merge this, since it was LGTM back in August.
