### ISSUE TITLE
After enabling Facets in Search API, the page directs you to Custom Blocks instead of Layout

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/facetapi#15]
After enabling Facets at `admin/config/search/search_api/index/default_node_index/facets`, the page shows the message

> To enable or arrange the facet blocks, visit the [blocks administration page](http://panettone.localhost:8888/admin/structure/block?destination=admin/config/search/search_api/index/default_node_index/facets).

This links sends you to the Custom Blocks. The correct location to enable the facet block is the Layout page (and perhaps it should explain that you must edit a layout to add the block).

**Comment by herbdool** [comment]
@argiepiano I've got a PR for this one.

**Comment by argiepiano** [comment]
LGTM!
