### ISSUE TITLE
Warning: Array to string conversion in FacetapiEmptyBehaviorAjaxFacets-

### ISSUE THREAD

**Issue by samgreco** [backdrop-contrib/facetapi#19]
Seeing this a lot.  I have empty facet behavior set to display ajax_facets wrapper.

Warning: Array to string conversion in FacetapiEmptyBehaviorAjaxFacets->execute() (line 49 of /home/xxxx/public_html/modules/ajax_facets/plugins/facetapi/empty_behavior_ajax_facets.inc).

Any clue?

**Comment by argiepiano** [comment]
This seems to be an Ajax Facet bug, not a FAcet API bug. I see you opened an issue there: https://github.com/backdrop-contrib/ajax_facets/issues/12

Closing here.
