### ISSUE TITLE
Permission to become Facet API maintainer

### ISSUE THREAD

**Issue by earlyburg** [backdrop-contrib/facetapi#6]
@docwilmot - I'm just making it official that we agreed that I would take over the maintainence of this module and that you are ok with it.

**Comment by docwilmot** [comment]
@klonos? Whats the process?

**Comment by klonos** [comment]
@docwilmot at minimum we need to add a licence and README.md in this repo. Then you can simply add @earlyburg's name to the maintainers list on the README, and also invite them via https://github.com/backdrop-contrib/facetapi/settings/access (I've already checked, and you have admin permission).

@earlyburg is already a member of the contrib authors group 👍 ...ref: https://github.com/backdrop-ops/contrib/issues/417

**Comment by earlyburg** [comment]
@klonos, @docwilmot 
README and LICENSE are already configured.
https://github.com/backdrop-contrib/facetapi/pull/4
It's part of my pull request

**Comment by klonos** [comment]
I see that @docwilmot has merged the PR, so @earlyburg you are now officially listed as a co-maintainer of this project.

@docwilmot you would also need to provide @earlyburg admin permission in https://github.com/backdrop-contrib/facetapi/settings/access. Would you like to do that yourself, or want me to assist?

**Comment by docwilmot** [comment]
done

**Comment by earlyburg** [comment]
@docwilmot Wooo! Thanks, I appreciate it.
